name: android-linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Checkout
        uses: actions/checkout@v4   

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: debug
        run: |
          set -x
          which adb || true
          find "$ANDROID_HOME" -name adb

      - name: Install GMD image for baseline profile generation
        run: |
          set -x
          yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager "system-images;android-33;aosp_atd;x86_64"

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Create emulator
        run: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n emu -k "system-images;android-33;aosp_atd;x86_64" --force

      - name: List emulator
        run: |
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Start emulator
        timeout-minutes: 60
        run: |
          set -x
          ADB="$(find "$ANDROID_HOME" -name adb | head -1)"
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd emu -no-snapshot &
          echo "Emulator starting"
          $ADB wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
          echo "Emulator started"
          $ADB devices
          $ADB shell getprop ro.product.cpu.abi
