name: artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          date > chrome-1.txt
          date > chrome-2.txt
          date > chrome-3.txt

          cat chrome-*.txt

      - uses: actions/upload-artifact@v4
        with:
          name: chrome
          path: |
            chrome-*.txt


  update-assets:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: chrome

      - run: |
          ls -alh

