name: chrome

on:
  workflow_dispatch:

env:
  LC_ALL: en_US.UTF-8

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          echo 111
          date
          pwd
          echo a123 | grep -oP '\d+'
      - run: |
          # Invoke-WebRequest -Uri 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile 'C:\chrome_installer.exe'
          # Start-Process -FilePath 'C:/chrome_installer.exe' -Args '--silent', '--install' -Wait
          cd $env:temp
          $Path = $env:TEMP
          $Installer = "chrome_installer.exe"
          Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $Path$Installer
          Start-Process -FilePath $Path$Installer -Args "/silent /install" -Verb RunAs -Wait
          Remove-Item $Path$Installer

      - run: |
          # gci env:* | sort-object name
          Get-ChildItem -Path $env:LOCALAPPDATA -Filter chrome.exe -Recurse -ErrorAction SilentlyContinue -Force
          Get-ChildItem -Path $env:ProgramFiles\Google -Filter chrome.exe -Recurse -ErrorAction SilentlyContinue -Force
          Get-ChildItem -Path ${env:ProgramFiles(x86)}\Google -Filter chrome.exe -Recurse -ErrorAction SilentlyContinue -Force

      - run: |
          # https://stackoverflow.com/a/36934083
          # Start-Process -FilePath "C:\Program Files\Google\Chrome\Application\chrome.exe" -Args "-incognito https://httpbin.org/get"
          $proc = Start-Process -FilePath "C:\Program Files\Google\Chrome\Application\chrome.exe" -Args "-incognito https://httpbin.org/get" -PassThru
      
          # keep track of timeout event
          $timeouted = $null # reset any previously set timeout
      
          # wait up to x seconds for normal termination
          $proc | Wait-Process -Timeout 10 -ErrorAction SilentlyContinue -ErrorVariable timeouted
          if ($timeouted)
          {
              # terminate the process
              $proc | kill
      
              echo timeouted
          }

          echo $proc.ExitCode
