name: chrome

on:
  workflow_dispatch:

env:
  LC_ALL: en_US.UTF-8

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          echo 111
          date
          pwd
          echo a123 | grep -oP '\d+'
