name: chrome

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          echo 111
          date
          echo a123 | grep -oP '\d+'
          pwd
