name: debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo du --max-depth=1 /
      - run: sudo du --max-depth=2 /
      - run: sudo du --max-depth=3 /
      - run: sudo du --max-depth=1 ~
      - run: sudo du --max-depth=2 ~
      - run: sudo du --max-depth=3 ~
      - run: docker images
