name: debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
      - name: (Debug)
        run: |
          git clone -b v0.43.17-alpha --depth=1 https://github.com/anyproto/anytype-ts
          cd anytype-ts
          npm i
          git status
          git diff
