name: dynamic-matrix

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.dataStep.outputs.myoutput }}
    steps:
      - id: dataStep
        run: |
          echo 'myoutput={"target":[{"version": "124", "url": "url1"},{"version": "123", "url": "url2"}]}' >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.mymatrix) }}
    steps:
      - run: echo ${{matrix.target.version}} - ${{matrix.target.url}}
