name: pyexe

on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        default: ''
      cli:
        type: string
        required: true
        default: 'python -m PyInstaller foo.py -n foo -F'
jobs:
  build:
    runs-on: 'windows-2019'

    steps:
      - uses: actions/checkout@v4
        with:
          repository: '${{ inputs.repo }}'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run a multi-line script
        run: |
          ${{ inputs.cli }}
